services:

  api:
    container_name: tournaments-api
    build:
      context: ./API/
      dockerfile: Dockerfile
      target: development
      args:
        - BUILDKIT_INLINE_CACHE=0
    user: vscode
    volumes:
      - ./API:/workspace
    entrypoint: [ "/usr/local/bin/entrypoint.sh" ]
    command: [ "tail", "-f", "/dev/null" ]
    ports:
      - 3000:3000
      - 3001:3001
    expose:
      - 3000
      - 3001
    networks:
      - development

  identity-service:
    container_name: tournaments-identity-service
    build:
      context: ./IdentityService/
      dockerfile: Dockerfile
      target: development
      args:
        - BUILDKIT_INLINE_CACHE=0
    user: vscode
    volumes:
      - ./IdentityService:/workspace
    entrypoint: [ "/usr/local/bin/entrypoint.sh" ]
    command: [ "tail", "-f", "/dev/null" ]
    ports:
      - 5001
    expose:
      - 5001
    networks:
      - development

  database:
    container_name: tournaments-db
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_DATABASE: "DevelopmentDB"
      MSSQL_SA_PASSWORD: "N&DevelopmentPassword"
    networks:
      - development

networks:
  development:
    driver: bridge
