services:

  api:
    container_name: tournaments-api
    build:
      dockerfile: ./API/Dockerfile
      args:
        - BUILDKIT_INLINE_CACHE=0
    user: vscode
    command: "tail -f /dev/null"
    environment:
      - DOTNET_ENVIRONMENT=Development
    networks:
      - development

  identity-service:
    container_name: tournaments-identity-service
    build:
      dockerfile: ./IdentityService/Dockerfile
      args:
        - BUILDKIT_INLINE_CACHE=0
    user: vscode
    command: "tail -f /dev/null"
    environment:
      - DOTNET_ENVIRONMENT=Development
    networks:
      - development
      
  database:
    container_name: tournaments-db
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_DATABASE: "DevelopmentDB"
      MSSQL_SA_PASSWORD: "N&DevelopmentPassword"
    networks:
      - development

networks:
  development:
    driver: bridge
