services: 

  api:
    container_name: tournaments-api
    image: "mcr.microsoft.com/devcontainers/dotnet:1-8.0-bookworm"
    command: "tail -f /dev/null"
    environment:
      - DOTNET_ENVIRONMENT=Development
    volumes:
      - .:/workspace
    networks:
        - development

  database: 
    container_name: tournaments-db
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_DATABASE: "DevelopmentDB"
      MSSQL_SA_PASSWORD: "N&DevelopmentPassword"
    networks:
      - development

networks:
  development:
    driver: bridge
